#!/bin/bash -
# .bash_profile

## Get the aliases and functions
#if [ -f ~/.bashrc ]; then
	#. ~/.bashrc
#fi

# get third bash profile
if [[ -f ~/.bamboo ]]; then
    . ~/.bamboo
fi


# User specific environment and startup programs
export mypy=~/grocery-shop/language/python/
export mygcc=~/grocery-shop/language/gcc/
export mysh=~/grocery-shop/language/shell/
export myja=~/grocery-shop/language/java/
export algo=~/grocery-shop/algorithm/
export dst=~/grocery-shop/data-structure/
export bamboo=~/grocery-shop/bamboo/
export share=~/share/
export work=~/work/
export waf=~/work/job/ngtos/SE/TOPWAF/
export job=~/work/job/
export py=/usr/local/python/lib/python2.7/site-packages/

# PATH
if [[ -d "$HOME/.local/bin" ]]; then
    PATH=$HOME/.local/bin:$PATH
fi
if [[ -d "/usr/local/nginx/sbin/" ]]; then
    PATH=/usr/local/nginx/sbin:$PATH
fi
if [[ -d "/usr/local/mysql/bin/" ]]; then
    PATH=/usr/local/mysql/bin/:$PATH
fi
if [[ -d "/usr/local/python/bin/" ]]; then
    PATH=$PATH:/usr/local/python/bin/
fi
export PATH

# svn configure
export SVN_EDITOR=vim

# java configure
export JAVA_HOME=/usr/local/java/jdk1.7.0_71
export CLASSPATH=.:%JAVA_HOME%/lib/dt.jar:%JAVA_HOME%/lib/tools.jar
export PATH=$PATH:$JAVA_HOME/bin

# maven configure
export M2_HOME=/usr/local/apache-maven
export M2=$M2_HOME/bin 
export PATH=$M2:$PATH

# zookeeper configure
export ZOOKEEPER_HOME=/usr/local/zookeeper
export PATH=$ZOOKEEPER_HOME/bin:$PATH

# storm configure
export STORM_HOME=/usr/local/storm
export PATH=$STORM_HOME/bin:$PATH

# streamparse
export LEIN_ROOT=0

# set vpn
nohup sslocal -s sg02-54.ssv7.net -p 24226 -b 127.0.0.1 -l 1080 -k LbEZs7f4NfLS -m aes-256-cfb &

ulimit -c unlimited
