#!/bin/bash -
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# get third bash profile
if [[ -f ~/.bamboo ]]; then
    . ~/.bamboo
fi


# User specific environment and startup programs
export mypy=~/grocery-shop/language/python/
export mygcc=~/grocery-shop/language/gcc/
export mysh=~/grocery-shop/language/shell/
export myja=~/grocery-shop/language/java/
export algo=~/grocery-shop/algorithm/
export bamboo=~/grocery-shop/bamboo/
export share=~/share/
export work=~/workspace/
export waf=~/workspace/job/SE/TOPWAF/
export job=~/work/job/ossdev/
export py=/usr/local/python/lib/python2.7/site-packages/

# other
PATH=$PATH:$HOME/bin:/usr/local/nginx/sbin/:/usr/local/mysql/bin/
PATH=$PATH:/usr/local/python/bin/
export PATH

# svn configure
export SVN_EDITOR=vim

# java configure
export JAVA_HOME=/usr/local/java/jdk1.7.0_71
export CLASSPATH=.:%JAVA_HOME%/lib/dt.jar:%JAVA_HOME%/lib/tools.jar
export PATH=$PATH:$JAVA_HOME/bin

# maven configure
export M2_HOME=/usr/local/apache-maven
export M2=$M2_HOME/bin 
export PATH=$M2:$PATH

ulimit -c unlimited
