#!/bin/bash - 
#===============================================================================
#
#          FILE: test.sh
# 
#         USAGE: ./test.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: unlessbamboo (?), unlessbamboo@gmail.com
#  ORGANIZATION: 
#       CREATED: 2016年01月15日 15:56
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

err()                                                                           
{
    local   stdfile="/data/logs/bamboo-install.log"
    if [[ ! -f "${stdfile}" ]];then
        touch "${stdfile}"
    fi
    echo "+++++++[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@"
    echo "+++++++[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >>"${stdfile}"
    exit 1
}

generateTags()
{
    # generate tag file for lookupfile plugin
    # !_TAG_FILE_SORTED表示此tags文件经过排序
    echo -e "!_TAG_FILE_SORTED\t2\t/2=foldcase/" > filenametags
    # find查找所有非png/gif的文件并按指定的格式打印，最后重新排序放入输出文件中
    find . -not -regex '.*\.\(png\|gif\)' -type f -printf "%f\t%p\t1\n" | sort -f >> filenametags 
}

generateTags
